### ISSUE TITLE
Refine UART emulation

### ISSUE THREAD

**Issue by jserv** [sysprog21/kvm-host#15]
[tomu](https://github.com/thomasbarrett/tomu) emulates a 16550A UART device with `epoll`.
```
    epoll <──────── eventfd <─────╮
                                  │
               ╭──────────────╮   │
     read <─── │ │ │ fifo │ │ │ <─┴─ out
(nonblocking)  ╰──────────────╯
               ╭──────────────╮
    write ───> │ │ │ fifo │ │ │ ───> in
(nonblocking)  ╰──────────────╯
```

It would be great if we can learn from this project.

**Comment by yanjiew1** [comment]
I have re-implemented the serial device using epoll and eventfd approach.
This is the pull request:
https://github.com/sysprog21/kvm-host/pull/16
