### ISSUE TITLE
Handle Ctrl-x a sequence to exit

### ISSUE THREAD

**Issue by jserv** [sysprog21/kvm-host#25]
Currently, when Ctrl-C is pressed, kvm-host terminates unexpectedly, leading to usability issues. To address this problem, we can implement the same behavior as QEMU, where the key sequence Ctrl-X followed by 'A' is used.

Reference:
* [Handle UART input with termios](https://github.com/jserv/semu/pull/17)

**Comment by yanjiew1** [comment]
The key sequence to terminate QEMU should be Ctrl-a x.

I have sent a pull request #30, which implements the key sequence ctrl-a x.
